version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: repairtrace
      POSTGRES_USER: repairtrace_user
      POSTGRES_PASSWORD: repairtrace_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=repairtrace
      - DB_USER=repairtrace_user
      - DB_PASS=repairtrace_password
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis

  celery:
    build: ./backend
    command: celery -A core_config worker -l info
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=db
      - DB_NAME=repairtrace
      - DB_USER=repairtrace_user
      - DB_PASS=repairtrace_password
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis
      - api

volumes:
  postgres_data:
