# Generated by Django 6.0.6 on 2026-09-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_systemnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnotification',
            name='action_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
