# Generated by Django 6.0.6 on 2026-09-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_subscriptionplan_customerprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('CHECKED_IN', 'Checked In'), ('DIAGNOSIS', 'Diagnosis'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('AWAITING_PARTS', 'Parts Pending'), ('IN_WORKSHOP', 'In Workshop'), ('QUALITY_CHECK', 'Quality Check'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CHECKED_IN', max_length=50),
        ),
    ]
