# Generated by Django 6.0.6 on 2026-09-28 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aiusagelog_technicianphoto_aifinding_vehicleqrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianphoto',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tech_photos', to='core.vehicleinspection'),
        ),
    ]
