# Generated by Django 5.0.3 on 2026-10-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_technicianphoto_inspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Request'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked In'), ('DIAGNOSIS', 'Diagnosis & Inspection'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('AWAITING_PARTS', 'Parts Pending'), ('IN_WORKSHOP', 'In Workshop (In Progress)'), ('QUALITY_CHECK', 'Quality Check'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='CHECKED_IN', max_length=50),
        ),
    ]
