# Generated by Django 6.0.6 on 2026-10-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_serviceorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_documents/'),
        ),
    ]
