# Generated by Django 6.0.6 on 2026-10-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_vehicledocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueevidence',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='issue_evidence/'),
        ),
        migrations.AlterField(
            model_name='issueevidence',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
